version: '3.8'

services:
  canana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - canana-network

networks:
  canana-network:
    driver: bridge